### ISSUE TITLE
Request flask-login 0.2.11

### ISSUE THREAD

**Issue by sodre** [conda-forge/flask-login-feedstock#5]
Would it be possible to start a branch for 0.2.x series as well? I am trying to build the conda package for apache's airflow and it has a pinned dependency on that. I tried your latest version but airflow threw an exception.

**Comment by pmlandwehr** [comment]
Hey, good luck! I started an airflow build ages ago but never finished it. This is in progress now: https://github.com/conda-forge/flask-login-feedstock/issues/5

**Comment by sodre** [comment]
Thank you for doing this so quickly. 

Do you have any guidance on supporting the *many* optional dependencies for airflow, i.e. the stuff in []? 

I know Anaconda is working on getting something done, but does it make sense to create a few meta packages like airflow-celery, airflow-hadoop, aiflow-emr, etc...

**Comment by pmlandwehr** [comment]
There's nothing consistent across conda-forge about this. I lean towards
the "include everything" style, but that's part of the reason why I never
finished airflow. You might want to investigate conda's metapackaging
capabilities to see about creating a number of different packages for the
different extras configurations.

**Comment by sodre** [comment]
Got it! Thanks.

I am closing this since you already created the branch!
